-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

ALTER TABLE IF EXISTS public.barang
    ADD CONSTRAINT barang FOREIGN KEY (kode_barang)
    REFERENCES public.sales (id_barang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pelanggan
    ADD CONSTRAINT pelanggan FOREIGN KEY (id_customer)
    REFERENCES public.sales (id_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pelanggan
    ADD CONSTRAINT pelanggan FOREIGN KEY (id_group)
    REFERENCES public.sales (id_group) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT penjualan FOREIGN KEY (id_invoice)
    REFERENCES public.sales (id_invoice) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT penjualan FOREIGN KEY (tanggal)
    REFERENCES public.sales (tanggal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT penjualan FOREIGN KEY (jumlah_barang)
    REFERENCES public.sales (jumlah_barang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT penjualan FOREIGN KEY (harga)
    REFERENCES public.sales (harga) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.penjualan
    ADD CONSTRAINT penjualan FOREIGN KEY (mata_uang)
    REFERENCES public.sales (mata_uang) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;